Implement assertfailed
diffplug/selfie pull request #355
Opened 2024-04-25 19:21 UTC by Trickybrain

Implement assertfailed

2024-04-26 15:53 UTC, nedtwigg requested changes
Good progress, needs some tweaks.

2024-04-26 15:53 UTC, nedtwigg commented on python/pytest-selfie/pytest_selfie/plugin.py
> +        actual_str = self._nullable_to_string(actual, "(null)")
The `"(null)"` should be `""`

https://github.com/diffplug/selfie/blob/e6c59053316e3492b3552a5dcf54c9ba598ee7e3/jvm/selfie-runner-kotest/src/commonMain/kotlin/com/diffplug/selfie/kotest/FSOkio.kt#L47-L48

2024-04-26 15:53 UTC, nedtwigg commented on python/pytest-selfie/pytest_selfie/plugin.py
> +            return self._comparison_assertion(message, "(null)", "(null)")
Not quite. We don't want to pass `"(null)", "(null)"`, we want to pass `"(null)"` as the default value if the thing is null

https://github.com/diffplug/selfie/blob/e6c59053316e3492b3552a5dcf54c9ba598ee7e3/jvm/selfie-runner-kotest/src/commonMain/kotlin/com/diffplug/selfie/kotest/FSOkio.kt#L51-L53

2024-04-26 15:53 UTC, nedtwigg commented on python/pytest-selfie/pytest_selfie/plugin.py
> +        return AssertionError(error_message)
In pytest, a comparison assertion should be `assert expected == actual, msg`, see https://github.com/diffplug/selfie/issues/299#issue-2226257195

2024-04-29 23:48 UTC, nedtwigg commented
If this feedback is confusing and you would rather work on the `to_match_disk` thing, let me know and I can wrap this up and you could start on the disk integration. Or if you'd like to finish this up that's fine too.

2024-05-01 19:18 UTC, nedtwigg approved these changes
I made a few more tweaks. Do they make sense @Trickybrain?

2024-05-01 19:29 UTC, Trickybrain commented
Yes it make more sense this way! Thank you!

2024-05-01 20:44 UTC, merged