cacheSelfie.py
diffplug/selfie pull request #356
Opened 2024-04-26 05:04 UTC by hssahota2

2024-04-26 17:15 UTC, nedtwigg requested changes
Very close! Have you tested it in our example project?

A good example would be something like:

```python
import random

cache_selfie(lambda: str(random.random())).to_be_TODO()
```

It should only update once, but when you add `_TODO` or `#selfieonce` it should rewrite and then stop updating.

2024-04-26 17:15 UTC, nedtwigg commented on python/selfie-lib/selfie_lib/Selfie.py
> +    return system_instance
We already have this, `_selfieSystem()`, look at line 34 just below this

2024-04-26 17:15 UTC, nedtwigg commented on python/selfie-lib/selfie_lib/Selfie.py
> +    return CacheSelfie(deferred_disk_storage, identity_roundtrip, to_cache)
This should call `cache_selfie_generic`.

2024-04-26 21:49 UTC, hssahota2 commented
I tried testing the cache selfie but right now I'm getting an assertion error

2024-04-29 14:53 UTC, nedtwigg approved these changes
Works great!

2024-04-29 16:16 UTC, merged